"""add chat memory table

Revision ID: 7c66c0970ef3
Revises: 
Create Date: 2025-06-04 06:01:15.506083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c66c0970ef3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_logs', 'chat_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('idx_chat_logs_chat_id'), table_name='chat_logs')
    op.create_index(op.f('ix_chat_logs_chat_id'), 'chat_logs', ['chat_id'], unique=False)
    op.create_index(op.f('ix_chat_logs_id'), 'chat_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_logs_id'), table_name='chat_logs')
    op.drop_index(op.f('ix_chat_logs_chat_id'), table_name='chat_logs')
    op.create_index(op.f('idx_chat_logs_chat_id'), 'chat_logs', ['chat_id'], unique=False)
    op.alter_column('chat_logs', 'chat_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
